### ISSUE TITLE
Please put the Chapter 3 Sharepoint list in excel format

### ISSUE THREAD

**Issue by hollyanneu2** [PacktPublishing/Learn-Microsoft-PowerApps#3]
Instead of powershell. My work will NOT allow the list imported via powershell. I can use excel to import. 

Thank you!

**Comment by Jubit-packt** [comment]
Hi @hollyanneu2, I'd suggest you try the method suggested in this article: https://support.microsoft.com/en-us/office/export-an-external-list-to-excel-fcbb5cdc-cf49-4131-8294-21bc25e66952 Hope that helps!
